repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      types: [text]
      exclude: "\\.ipynb$"
    - id: end-of-file-fixer
      types: [text]
      exclude: "\\.ipynb$"
    - id: check-yaml
      types: [yaml]
      exclude: "\\.ipynb$"
    - id: check-merge-conflict
      types: [text]
      exclude: "\\.ipynb$"
    - id: pretty-format-json
      types: [json]
      exclude: "\\.ipynb$"
      args: ["--autofix", "--indent", "2"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff-check
      args: ["--fix"]
      always_run: true
      types: [python]
      exclude: "\\.ipynb$"
    - id: ruff-format
      always_run: true
      types: [python]
      exclude: "\\.ipynb$"

- repo: https://github.com/PyCQA/pylint
  rev: v3.3.4
  hooks:
    - id: pylint
      args: ["--rcfile=.pylintrc"]
      types: [python]
      exclude: "\\.ipynb$"

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      args: ["--config-file", "mypy.ini"]
      always_run: true
      types: [python]
      exclude: "\\.ipynb$"