name: "Build and push docker container"

description: "A composite action that builds and pushes a docker container"

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  image_name:
    required: true
    description: "Docker image name (the part between the registry url and the image tag)"
  context:
    required: true
    description: "Docker build context"
  image_tag:
    required: true
    description: "tag for the image"
  base_image_name:
    required: false
    default: 'latest'
    description: "building docker image"
  base_image_tag:
    required: false
    default: 'latest'
    description: "tag to the docker image build"
  force_build:
    required: false
    default: 'false'
    description: "rebuild this image"
  dockerfile_name:
    description: 'here you can pass Dockerfile names, which are not called Dockerfile'
    required: false
    default: "Dockerfile"

outputs:
  success:
    description: "If build was successful"
    value: ${{ steps.success.outputs.success }}

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: Docker build with docker action
      uses: docker/build-push-action@v6
      with:
        build-args: |
          BASE_IMAGE=${{ inputs.base_image_name }}
          BASE_IMAGE_TAG=${{ inputs.base_image_tag }}
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile_name }}
        push: true
        tags: ghcr.io/Paradox3333/reusables/${{ inputs.image_name }}:${{ inputs.image_tag }}
    - id: success
      shell: bash
      run: echo "success=true" >> $GITHUB_OUTPUT
